### ISSUE TITLE
Warp does not get removed when destroyed by creeper

### ISSUE THREAD

**Issue by Philip2809** [Programie/SignWarper#1]
As title says, If [WarpTarget] sign is destroyed by a creeper the target still exists but there is no sign and when I try to create a new one with the same name it says it already exists

**Comment by Programie** [comment]
I just checked the code for that. And yes, currently there is nothing there to prevent the destruction of the sign. Sign might also be broken by removing the supporting block bellow or behind it.

I'm not sure what should be the correct behavior in such a case and need another opinion about that. Should the sign be destroyed (just like now) and the warp will be removed? Or should I prevent breaking the sign?

I have another plugin called [SaveMyXP](https://github.com/Programie/SaveMyXP) which also works with signs. In that plugin, I'm preventing breaking the sign to prevent the players loosing their XP saved on the sign. So it's possible to prevent it in this plugin, too. But as said, I'm not sure which behavior would be better.

**Comment by Programie** [comment]
I've fixed the issue by preventing breaking blocks by explosions, pistons and fire.

Please use version 1.3.0 of the plugin which now contains the fix.
